spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://varin.cn:3306/hututu
    username: root
    password: 123456

mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false # 下划线转驼峰
    # 如果项目无日志框架，可以考虑指定为 org.apache.ibatis.logging.stdout.StdOutImpl (请勿在实际生产中使用).
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      logic-delete-field: isDelete # 逻辑删除
      logic-delete-value: true # 为1删除
      logic-not-delete-value: false # 为0不删除
